# Generated by Django 2.2.26 on 2022-03-15 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crowdbotic_lite', '0001_initial'),
        ('subscription_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('crowdbotic_lite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_crowdbotic_lite', to='crowdbotic_lite.GenerateModels')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_plan', to='subscription_plan.SubscriptionPlans')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
